import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { createCsvTaskProcessor } from "../public/csv-background-tasks.js";
import { createCsvWorkerClient } from "../public/csv-worker-client.js";
import { downloadFileApi } from "../public/electron-bridge.js";
import { decodeResolveCsv, encodeResolveCsv, parseCsvText } from "../public/resolve-csv.js";
import { restoreCsvPreviewState, serializeCsvPreviewState } from "../public/task-persistence.js";

// The reviewed manifest is deliberately independent of production constants:
// generated bytes are compared to fixed length/hash/table evidence and are
// never written back by the tests.
const csvRoot = new URL("./fixtures/baseline/csv/", import.meta.url);
const manifest = JSON.parse(await readFile(new URL("manifest.json", csvRoot), "utf8"));

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function assertBytes(bytes, expected) {
  assert.equal(bytes.byteLength, expected.bytes, "CSV byte length drift");
  assert.equal(sha256(bytes), expected.sha256, "CSV SHA-256 drift");
}

function assertResolveTable(bytes, expected) {
  assertBytes(bytes, expected);
  const table = decodeResolveCsv(bytes);
  assert.deepEqual(table.format, expected.format);
  assert.deepEqual(table.headers, expected.headers);
  assert.deepEqual(table.rows, expected.rows);
  return table;
}

test("baseline source fixtures and round-trip bytes match the reviewed manifest", async () => {
  for (const [name, expected] of Object.entries(manifest.sources)) {
    const bytes = new Uint8Array(await readFile(new URL(name, csvRoot)));
    const table = assertResolveTable(bytes, expected);
    const roundTrip = encodeResolveCsv(table);
    assertBytes(roundTrip, expected.roundTrip);
  }
});

test("a deliberate one-byte mutation fails the reviewed CSV byte contract", async () => {
  const expected = manifest.sources["resolve-source.csv"];
  const bytes = new Uint8Array(await readFile(new URL("resolve-source.csv", csvRoot)));
  const mutated = bytes.slice();
  mutated[Math.floor(mutated.length / 2)] ^= 1;
  assert.notEqual(sha256(mutated), expected.sha256);
  assert.throws(() => assertBytes(mutated, expected), /CSV SHA-256 drift/);
});

test("baseline Resolve merge has exact bytes, multi-scene, widths, metadata, comments, edits, and unmatched rows", async () => {
  const source = new Uint8Array(await readFile(new URL("resolve-source.csv", csvRoot)));
  const processTask = createCsvTaskProcessor();
  processTask({ type: "decode-metadata", data: source });
  const output = processTask({
    type: "export-resolve",
    records: [
      { cardNumber: "A001", videoCode: "C001", scene: "1 / 2a", shot: "2", take: "3", takeStatus: "过" },
      { cardNumber: "A001", videoCode: "C002", scene: "1234", shot: "100", take: "11", takeStatus: "保" },
      { cardNumber: "A001", videoCode: "C404", scene: null, shot: "1", take: "1", takeStatus: "过" },
    ],
    slateMetadata: [{ materialKey: "A:1:1", sensorFps: "24", shootDay: "26-01-01" }],
    csvEdits: [["0:5", "edited note"]],
    fieldFormats: { scene: "XXX", shot: "XX", take: "XX" },
    comments: { goodTake: "YES", holdTake: "HOLD" },
  });
  assertResolveTable(output.bytes, manifest.outputs.mergedResolve);
});

test("baseline standalone export has exact UTF-16LE CRLF bytes and skips incomplete records", () => {
  const processTask = createCsvTaskProcessor();
  const output = processTask({
    type: "export-standalone",
    records: [
      { cardNumber: "A001", videoCode: "C001", scene: "37a", shot: "2", take: "11", comments: "HOLD" },
      { cardNumber: "A001", videoCode: "C002", scene: "1234", shot: "100", take: "3", comments: "YES" },
      { cardNumber: "A001", videoCode: "C003", scene: null, shot: "1", take: "1" },
    ],
    fieldFormats: { scene: "XXX", shot: "XX", take: "XX" },
    comments: { goodTake: "YES", holdTake: "HOLD" },
  });
  const expected = manifest.outputs.standalone;
  assertBytes(output.bytes, expected);
  const text = new TextDecoder("utf-16le").decode(output.bytes.subarray(2));
  const matrix = parseCsvText(text, expected.format.delimiter);
  assert.deepEqual(matrix[0], expected.headers);
  assert.deepEqual(matrix.slice(1), expected.rows);
  assert.equal(text.includes("\r\n"), true);
});

test("baseline CSV preview snapshot round-trips only valid sparse edit keys", () => {
  const snapshot = serializeCsvPreviewState({
    metadataTable: { headers: ["File Name", "Scene"], rows: [["A001C001.mov", "001"]], format: { encoding: "utf-8", delimiter: "," } },
    metadataFilename: "timeline.csv",
    csvEdits: new Map([["0:1", "002"], ["bad", "ignored"]]),
    slateMetadata: [{ materialKey: "A:1:1" }],
    slateWarnings: ["synthetic"],
    missingMetadataKeys: ["A:1:2"],
    slateDirectoryName: "Day 01",
  });
  const restored = restoreCsvPreviewState(snapshot);
  assert.deepEqual([...restored.csvEdits], [["0:1", "002"]]);
  assert.deepEqual(restored.metadataTable, snapshot.resolveCsvTable);
  assert.equal(restored.metadataFilename, "timeline.csv");
  assert.equal(restoreCsvPreviewState({ resolveCsvEdits: { bad: "value" } }), null);
});

test("baseline module Worker transfers ArrayBuffer, retains state, clears it, and classifies task errors", async () => {
  const previousSelf = globalThis.self;
  const listeners = new Map();
  const posted = [];
  globalThis.self = {
    addEventListener(type, callback) {
      listeners.set(type, callback);
    },
    postMessage(message, transfer = []) {
      posted.push({ message, transfer });
    },
  };
  try {
    await import(`../public/csv-worker.js?baseline=${Date.now()}`);
    const source = new Uint8Array(await readFile(new URL("resolve-source.csv", csvRoot)));
    listeners.get("message")({ data: { id: 1, task: { type: "decode-metadata", data: source } } });
    listeners.get("message")({ data: {
      id: 2,
      task: {
        type: "export-resolve",
        records: [{ cardNumber: "A001", videoCode: "C001", scene: "1", shot: "2", take: "3", takeStatus: "过" }],
        fieldFormats: { scene: "XXX", shot: "XX", take: "XX" },
        comments: { goodTake: "_OK", holdTake: "_KP" },
      },
    } });
    const transferred = posted.find((entry) => entry.message.id === 2);
    assert.ok(transferred.message.result.bytes instanceof ArrayBuffer);
    assert.equal(transferred.transfer[0], transferred.message.result.bytes);

    listeners.get("message")({ data: { id: 3, task: { type: "clear-metadata" } } });
    listeners.get("message")({ data: { id: 4, task: { type: "export-resolve", records: [] } } });
    assert.match(posted.find((entry) => entry.message.id === 4).message.error, /尚未载入有效的 Resolve CSV/);
  } finally {
    if (previousSelf === undefined) delete globalThis.self;
    else globalThis.self = previousSelf;
  }
});

test("baseline Worker client handles transfer, task errors, termination, and infrastructure-only fallback", async () => {
  let instance;
  class FakeWorker {
    constructor() {
      instance = this;
      this.listeners = new Map();
    }
    addEventListener(type, callback) { this.listeners.set(type, callback); }
    postMessage(message, transfer) { this.posted = { message, transfer }; }
    terminate() { this.terminated = true; }
  }

  const client = createCsvWorkerClient({ WorkerClass: FakeWorker });
  const buffer = new ArrayBuffer(4);
  const success = client.request({ type: "prime-metadata" }, [buffer]);
  instance.listeners.get("message")({ data: { id: 1, result: { ready: true } } });
  assert.deepEqual(await success, { ready: true });
  assert.equal(instance.posted.transfer[0], buffer);

  const taskFailure = client.request({ type: "unknown" });
  instance.listeners.get("message")({ data: { id: 2, error: "synthetic task error" } });
  await assert.rejects(taskFailure, (error) => error.csvWorkerTask === true && /synthetic task error/.test(error.message));

  const pending = client.request({ type: "decode-metadata" });
  client.terminate();
  await assert.rejects(pending, /CSV 后台 Worker 已停止/);
  assert.equal(instance.terminated, true);
  assert.equal(createCsvWorkerClient({ WorkerClass: null }), null);
  assert.equal(createCsvWorkerClient({ WorkerClass: class { constructor() { throw new Error("blocked"); } } }), null);
});

test("baseline typed-array subviews save only their exact byte range", async () => {
  const previous = globalThis.electronAPI;
  let saved;
  globalThis.electronAPI = {
    saveFile: async (_filename, data) => {
      saved = new Uint8Array(data);
      return { saved: true };
    },
  };
  try {
    const backing = new Uint8Array([9, 1, 2, 3, 8]);
    await downloadFileApi(backing.subarray(1, 4), "exact.csv");
    assert.deepEqual([...saved], [1, 2, 3]);
  } finally {
    if (previous === undefined) delete globalThis.electronAPI;
    else globalThis.electronAPI = previous;
  }
});
